const chartNL = {
    properties: {},
    tracks: [
      {
        layout: '5',
        type: 'MUSIC',
        key: '667312288',
        title: '(It Goes Like) Nanana (Edit)',
        subtitle: 'Peggy Gou',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/667312288/it-goes-like-nanana-edit',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '661217794',
        title: 'Esta Vida',
        subtitle: 'Marshmello & Farruko',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/661217794/esta-vida',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '657750716',
        title: 'Arranca (feat. Omega)',
        subtitle: 'Becky G.',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/657750716/arranca-feat-omega',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '653369691',
        title: 'Tattoo',
        subtitle: 'Loreen',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/653369691/tattoo',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '671859699',
        title: 'Плохая Девочка (Травма Фонк Remix)',
        subtitle: 'Винтаж Feat. Елена Корикова',
        share: [Object],
        hub: [Object],
        url: 'https://www.shazam.com/track/671859699/-',
        highlightsurls: {},
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '267429991',
        title: 'Makeba',
        subtitle: 'Jain',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/267429991/makeba',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '660372671',
        title: 'Džanum',
        subtitle: 'Teya Dora',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/660372671/d%C5%BEanum',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '659236090',
        title: 'Daylight',
        subtitle: 'David Kushner',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/659236090/daylight',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '665449473',
        title: 'How You Samba',
        subtitle: 'Kris Kross Amsterdam, Sofía Reyes & Tinie Tempah',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/665449473/how-you-samba',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '636319918',
        title: 'Wish You The Best',
        subtitle: 'Lewis Capaldi',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/636319918/wish-you-the-best',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '654295107',
        title: 'Miracle',
        subtitle: 'Calvin Harris & Ellie Goulding',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/654295107/miracle',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '644270294',
        title: 'People',
        subtitle: 'Libianca',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/644270294/people',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '668599234',
        title: 'Drifting',
        subtitle: 'Tiësto',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/668599234/drifting',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '657958604',
        title: 'Substitution (feat. Julian Perretta)',
        subtitle: 'Purple Disco Machine & Kungs',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/657958604/substitution-feat-julian-perretta',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '664253855',
        title: 'UNHEALTHY (feat. Shania Twain)',
        subtitle: 'Anne-Marie',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/664253855/unhealthy-feat-shania-twain',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '659559607',
        title: 'People (feat. Cian Ducrot)',
        subtitle: 'Libianca',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/659559607/people-feat-cian-ducrot',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '662681761',
        title: 'Chemical',
        subtitle: 'Post Malone',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/662681761/chemical',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '666082740',
        title: 'Padam Padam',
        subtitle: 'Kylie Minogue',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/666082740/padam-padam',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '659079133',
        title: 'Overcome',
        subtitle: 'Nothing But Thieves',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/659079133/overcome',
        highlightsurls: [Object],
        properties: {}
      },
      {
        layout: '5',
        type: 'MUSIC',
        key: '664169543',
        title: 'Good Love',
        subtitle: 'Hannah Laing & RoRo',
        share: [Object],
        images: [Object],
        hub: [Object],
        artists: [Array],
        url: 'https://www.shazam.com/track/664169543/good-love',
        highlightsurls: [Object],
        properties: {}
      }
    ]
  }

  module.exports =chartNL